name: Build & Deploy Web (Expo SDK 53)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Ensure image-size override
        run: |
          npm pkg delete dependencies.image-size || true
          npm pkg delete devDependencies.image-size || true
          npm pkg set overrides.image-size=1.0.2

      - name: Install dependencies
        run: npm ci

      - name: Export web build
        run: npm run export:web

      - name: Deploy to gh-pages branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: dist
          publish_branch: gh-pages